export const bookings = [
  {
    bookingId: "B001",
    courtName: "Court A",
    date: "2024-09-25",
    startTime: "14:00",
    endTime: "15:00",
    duration: "1 hour",
    customerName: "John Doe",
    contactInfo: "08123456789",
    status: "Confirmed",
    price: 500000,
    paymentStatus: "Paid",
    paymentMethod: "Credit Card",
    specialRequests: "No special requests",
  },
  {
    bookingId: "B002",
    courtName: "Court B",
    date: "2024-09-26",
    startTime: "16:00",
    endTime: "17:00",
    duration: "1 hour",
    customerName: "Jane Smith",
    contactInfo: "08234567890",
    status: "Pending",
    price: 450000,
    paymentStatus: "Pending",
    paymentMethod: "Cash",
    specialRequests: "Need a ball",
  },
  {
    bookingId: "B003",
    courtName: "Court A",
    date: "2024-09-27",
    startTime: "18:00",
    endTime: "19:00",
    duration: "1 hour",
    customerName: "Mike Johnson",
    contactInfo: "08345678901",
    status: "Canceled",
    price: 500000,
    paymentStatus: "Refunded",
    paymentMethod: "Bank Transfer",
    specialRequests: "Need cones for training",
  },
  {
    bookingId: "B004",
    courtName: "Court C",
    date: "2024-09-28",
    startTime: "15:00",
    endTime: "17:00",
    duration: "2 hours",
    customerName: "Emily Davis",
    contactInfo: "08123456789",
    status: "Confirmed",
    price: 1000000,
    paymentStatus: "Paid",
    paymentMethod: "E-wallet",
    specialRequests: "Need extra time for warm-up",
  },
  {
    bookingId: "B005",
    courtName: "Court B",
    date: "2024-09-29",
    startTime: "13:00",
    endTime: "14:30",
    duration: "1.5 hours",
    customerName: "Chris Brown",
    contactInfo: "08234567890",
    status: "Confirmed",
    price: 750000,
    paymentStatus: "Paid",
    paymentMethod: "Credit Card",
    specialRequests: "Reserved seats for spectators",
  },
  {
    bookingId: "B006",
    courtName: "Court A",
    date: "2024-09-30",
    startTime: "14:00",
    endTime: "15:00",
    duration: "1 hour",
    customerName: "Sophia Wilson",
    contactInfo: "08345678901",
    status: "Pending",
    price: 500000,
    paymentStatus: "Pending",
    paymentMethod: "Bank Transfer",
    specialRequests: "No special requests",
  },
  {
    bookingId: "B007",
    courtName: "Court C",
    date: "2024-10-01",
    startTime: "17:00",
    endTime: "18:00",
    duration: "1 hour",
    customerName: "David Clark",
    contactInfo: "08123456789",
    status: "Confirmed",
    price: 550000,
    paymentStatus: "Paid",
    paymentMethod: "E-wallet",
    specialRequests: "Provide drinking water",
  },
  {
    bookingId: "B008",
    courtName: "Court B",
    date: "2024-10-02",
    startTime: "16:30",
    endTime: "17:30",
    duration: "1 hour",
    customerName: "Olivia Martinez",
    contactInfo: "08234567890",
    status: "Confirmed",
    price: 600000,
    paymentStatus: "Paid",
    paymentMethod: "Credit Card",
    specialRequests: "Reserved locker for belongings",
  },
  {
    bookingId: "B009",
    courtName: "Court A",
    date: "2024-10-03",
    startTime: "18:30",
    endTime: "19:30",
    duration: "1 hour",
    customerName: "Ethan Harris",
    contactInfo: "08345678901",
    status: "Pending",
    price: 500000,
    paymentStatus: "Pending",
    paymentMethod: "Cash",
    specialRequests: "Late booking, please confirm quickly",
  },
  {
    bookingId: "B010",
    courtName: "Court C",
    date: "2024-10-04",
    startTime: "15:00",
    endTime: "16:30",
    duration: "1.5 hours",
    customerName: "Ava Clark",
    contactInfo: "08123456789",
    status: "Confirmed",
    price: 800000,
    paymentStatus: "Paid",
    paymentMethod: "Bank Transfer",
    specialRequests: "Need first aid kit available",
  },
];

export const featuredData = [
  {
    image: "https://picsum.photos/300/300",
    title: "Main Street Resort",
    location: "Dhaka, Bangladesh",
  },
  {
    image: "https://picsum.photos/300/300",
    title: "Ocean View Hotel",
    location: "Cox's Bazar, Bangladesh",
  },
  {
    image: "https://picsum.photos/300/300",
    title: "Mountain Retreat",
    location: "Sylhet, Bangladesh",
  },
  {
    image: "https://picsum.photos/300/300",
    title: "City Center Inn",
    location: "Chittagong, Bangladesh",
  },
  {
    image: "https://picsum.photos/300/300",
    title: "Lakeside Cottage",
    location: "Rajshahi, Bangladesh",
  },
  {
    image: "https://picsum.photos/300/300",
    title: "Heritage Palace",
    location: "Khulna, Bangladesh",
  },
];


export const totalVisit = [
  {
    name: "Total Visit",
    value: 240,
    change: 25,
    changeType: "up",
  },
  {
    name: "Cancel Travel",
    value: 15,
    change: 18,
    changeType: "down",
  },
  {
    name: "In Queue",
    value: 24,
    change: 14,
    changeType: "up",
  },
  {
    name: "Interested Places",
    value: 56,
    change: 28,
    changeType: "up",
  },
];

export const futsalFields = [
  {
    id: 1,
    name: "Lapangan 1",
    type: "Rumput Sintetis",
    location: "Jl. Sudirman No.10",
    size: "25x15 m",
    capacity: 10,
    price: 200000,
    availability: "Tersedia",
    facilities: "Kamar Mandi, Loker",
    hours: "08:00 - 22:00",
    notes: "Lapangan baru direnovasi",
  },
  {
    id: 2,
    name: "Lapangan 2",
    type: "Semen",
    location: "Jl. Thamrin No.15",
    size: "30x20 m",
    capacity: 12,
    price: 250000,
    availability: "Tersedia",
    facilities: "Loker, Kantin",
    hours: "07:00 - 23:00",
    notes: "Cocok untuk turnamen",
  },
  // Tambahkan lebih banyak data hingga 10 data dummy
];

export const lapanganFutsal = [
  {
    nama_lapangan: "Lapangan A",
    jenis_lapangan: "Futsal",
    lokasi: "Ruang A",
    ukuran_lapangan: "25x15",
    kapasitas_pemain: 10,
    fasilitas: "Ruang ganti, Kamar mandi, Parkir",
    data_penyewaan: "John Doe",
    harga_sewa_per_jam: 150000,
    ketersediaan: true,
    waktu_operasional: "08:00 - 22:00",
    keterangan_lainnya: "Lapangan baru direnovasi",
  },
  {
    nama_lapangan: "Lapangan B",
    jenis_lapangan: "Futsal",
    lokasi: "Ruang B",
    ukuran_lapangan: "25x15",
    kapasitas_pemain: 12,
    fasilitas: "Ruang ganti, Kamar mandi",
    data_penyewaan: "Jane Smith",
    harga_sewa_per_jam: 200000,
    ketersediaan: false,
    waktu_operasional: "08:00 - 22:00",
    keterangan_lainnya: "Lapangan sering penuh",
  },
  {
    nama_lapangan: "Lapangan C",
    jenis_lapangan: "Futsal",
    lokasi: "Ruang C",
    ukuran_lapangan: "25x15",
    kapasitas_pemain: 8,
    fasilitas: "Parkir, Kamar mandi",
    data_penyewaan: "Michael Johnson",
    harga_sewa_per_jam: 120000,
    ketersediaan: true,
    waktu_operasional: "08:00 - 22:00",
    keterangan_lainnya: "Lapangan bersih dan terawat",
  },
  {
    nama_lapangan: "Lapangan D",
    jenis_lapangan: "Futsal",
    lokasi: "Ruang D",
    ukuran_lapangan: "25x15",
    kapasitas_pemain: 10,
    fasilitas: "Ruang ganti, Wi-Fi",
    data_penyewaan: "Emily Davis",
    harga_sewa_per_jam: 180000,
    ketersediaan: true,
    waktu_operasional: "08:00 - 22:00",
    keterangan_lainnya: "Lapangan dengan pencahayaan baik",
  },
  {
    nama_lapangan: "Lapangan E",
    jenis_lapangan: "Futsal",
    lokasi: "Ruang A",
    ukuran_lapangan: "25x15",
    kapasitas_pemain: 10,
    fasilitas: "Ruang ganti, Kamar mandi, Parkir",
    data_penyewaan: "David Wilson",
    harga_sewa_per_jam: 160000,
    ketersediaan: false,
    waktu_operasional: "08:00 - 22:00",
    keterangan_lainnya: "Lapangan sering digunakan untuk turnamen",
  },
  {
    nama_lapangan: "Lapangan F",
    jenis_lapangan: "Futsal",
    lokasi: "Ruang B",
    ukuran_lapangan: "25x15",
    kapasitas_pemain: 12,
    fasilitas: "Ruang ganti, Kamar mandi, Wi-Fi",
    data_penyewaan: "Sarah Brown",
    harga_sewa_per_jam: 190000,
    ketersediaan: true,
    waktu_operasional: "08:00 - 22:00",
    keterangan_lainnya: "Lapangan dengan fasilitas lengkap",
  },
  {
    nama_lapangan: "Lapangan G",
    jenis_lapangan: "Futsal",
    lokasi: "Ruang C",
    ukuran_lapangan: "25x15",
    kapasitas_pemain: 10,
    fasilitas: "Parkir, Kamar mandi",
    data_penyewaan: "Chris Martin",
    harga_sewa_per_jam: 140000,
    ketersediaan: true,
    waktu_operasional: "08:00 - 22:00",
    keterangan_lainnya: "Lapangan nyaman untuk bermain",
  },
  {
    nama_lapangan: "Lapangan H",
    jenis_lapangan: "Futsal",
    lokasi: "Ruang D",
    ukuran_lapangan: "25x15",
    kapasitas_pemain: 8,
    fasilitas: "Ruang ganti, Kamar mandi",
    data_penyewaan: "Jessica Taylor",
    harga_sewa_per_jam: 130000,
    ketersediaan: false,
    waktu_operasional: "08:00 - 22:00",
    keterangan_lainnya: "Lapangan sering penuh",
  },
  {
    nama_lapangan: "Lapangan I",
    jenis_lapangan: "Futsal",
    lokasi: "Ruang A",
    ukuran_lapangan: "25x15",
    kapasitas_pemain: 10,
    fasilitas: "Ruang ganti, Wi-Fi, Parkir",
    data_penyewaan: "Daniel Lee",
    harga_sewa_per_jam: 175000,
    ketersediaan: true,
    waktu_operasional: "08:00 - 22:00",
    keterangan_lainnya: "Lapangan dengan suasana yang menyenangkan",
  },
  {
    nama_lapangan: "Lapangan J",
    jenis_lapangan: "Futsal",
    lokasi: "Ruang B",
    ukuran_lapangan: "25x15",
    kapasitas_pemain: 10,
    fasilitas: "Ruang ganti, Kamar mandi, Wi-Fi",
    data_penyewaan: "Laura Green",
    harga_sewa_per_jam: 160000,
    ketersediaan: true,
    waktu_operasional: "08:00 - 22:00",
    keterangan_lainnya: "Lapangan dengan banyak pengunjung",
  },
  {
    nama_lapangan: "Lapangan K",
    jenis_lapangan: "Futsal",
    lokasi: "Ruang C",
    ukuran_lapangan: "25x15",
    kapasitas_pemain: 12,
    fasilitas: "Ruang ganti, Kamar mandi",
    data_penyewaan: "Mark White",
    harga_sewa_per_jam: 150000,
    ketersediaan: false,
    waktu_operasional: "08:00 - 22:00",
    keterangan_lainnya: "Lapangan dengan suasana yang tenang",
  },
  {
    nama_lapangan: "Lapangan L",
    jenis_lapangan: "Futsal",
    lokasi: "Ruang D",
    ukuran_lapangan: "25x15",
    kapasitas_pemain: 10,
    fasilitas: "Ruang ganti, Wi-Fi, Parkir",
    data_penyewaan: "Sophia Black",
    harga_sewa_per_jam: 180000,
    ketersediaan: true,
    waktu_operasional: "08:00 - 22:00",
    keterangan_lainnya: "Lapangan dengan fasilitas modern",
  },
  {
    nama_lapangan: "Lapangan M",
    jenis_lapangan: "Futsal",
    lokasi: "Ruang A",
    ukuran_lapangan: "25x15",
    kapasitas_pemain: 10,
    fasilitas: "Ruang ganti, Kamar mandi, Parkir",
    data_penyewaan: "James Brown",
    harga_sewa_per_jam: 140000,
    ketersediaan: true,
    waktu_operasional: "08:00 - 22:00",
    keterangan_lainnya: "Lapangan dengan banyak fasilitas",
  },
  {
    nama_lapangan: "Lapangan N",
    jenis_lapangan: "Futsal",
    lokasi: "Ruang B",
    ukuran_lapangan: "25x15",
    kapasitas_pemain: 12,
    fasilitas: "Ruang ganti, Kamar mandi, Wi-Fi",
    data_penyewaan: "Olivia Johnson",
    harga_sewa_per_jam: 190000,
    ketersediaan: false,
    waktu_operasional: "08:00 - 22:00",
    keterangan_lainnya: "Lapangan dengan suasana yang ceria",
  },
  {
    nama_lapangan: "Lapangan O",
    jenis_lapangan: "Futsal",
    lokasi: "Ruang C",
    ukuran_lapangan: "25x15",
    kapasitas_pemain: 10,
    fasilitas: "Ruang ganti, Kamar mandi",
    data_penyewaan: "Liam Smith",
    harga_sewa_per_jam: 130000,
    ketersediaan: true,
    waktu_operasional: "08:00 - 22:00",
    keterangan_lainnya: "Lapangan dengan banyak pengunjung",
  },
  {
    nama_lapangan: "Lapangan P",
    jenis_lapangan: "Futsal",
    lokasi: "Ruang D",
    ukuran_lapangan: "25x15",
    kapasitas_pemain: 10,
    fasilitas: "Ruang ganti, Kamar mandi, Parkir",
    data_penyewaan: "Emma Wilson",
    harga_sewa_per_jam: 160000,
    ketersediaan: true,
    waktu_operasional: "08:00 - 22:00",
    keterangan_lainnya: "Lapangan dengan suasana yang nyaman",
  },
];
